# Process setup per JM
# https://montemagno.com/continuous-integration-delivery-for-net-libraries-with-vsts/

# Set buildnumber here and add versioningScheme: byBuildNumber to NugetCommand@2
name: 3.0.0$(rev:.r)

trigger:
- master

# From starter template
pool:
  vmImage: 'ubuntu-latest'

steps:

# JM specified version 4.5.1 but can use latest default
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '4.5.1'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: '86153590-b7da-4504-b416-f06a4b16a355'
    versioningScheme: byBuildNumber


- task: MSBuild@1
  inputs:
    solution: '**/XamarinFormsMvvmAdaptor.csproj'
    configuration: 'Release'
    msbuildArguments: '/t:restore;build;pack /p:PackageVersion=$(Build.BuildNumber)-beta /p:PackageOutputPath=$(build.artifactstagingdirectory)/beta /p:AssemblyFileVersion=$(Build.BuildNumber)'


- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.UnitTests.csproj'
    arguments: '--no-build --configuration Release'
    testRunTitle: 'Unit Tests'

- task: MSBuild@1
  inputs:
    solution: '**/XamarinFormsMvvmAdaptor.csproj'
    configuration: 'Release'
    msbuildArguments: '/t:restore;build;pack /p:PackageVersion=$(Build.BuildNumber) /p:PackageOutputPath=$(build.artifactstagingdirectory)/public  /p:AssemblyFileVersion=$(Build.BuildNumber)'

#Maybe you want to add unit test runners here

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: '**\bin\Release\**\*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'